name: flavour_town_subs_flutter_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  date_format: ^2.0.7
  easy_url_launcher: ^0.0.7
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.5.9
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/onboarding_images/
    - lib/assets/product_images/